# Generated by Django 3.1.3 on 2020-12-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coworker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('picture', models.ImageField(default='dashboard-BG.jpg', upload_to='')),
                ('email', models.CharField(max_length=150)),
                ('social', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=250)),
            ],
        ),
    ]
