# Generated by Django 3.1.3 on 2020-11-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Vegan', 'Vegetarian')], max_length=200, null=True)),
                ('rating', models.FloatField(null=True)),
                ('tags', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('rating', models.FloatField(null=True)),
                ('tags', models.CharField(max_length=200, null=True)),
                ('affordability', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
