# Generated by Django 3.1.3 on 2020-11-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201108_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.FloatField(max_length=400, null=True),
        ),
    ]
