# Generated by Django 3.1.4 on 2020-12-11 13:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201211_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='rating',
            new_name='averageRating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('Restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.restaurant')),
            ],
        ),
    ]
