# Generated by Django 3.1.3 on 2020-11-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201122_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_picture',
            field=models.ImageField(default='dashboard-BG.jpg', null=True, upload_to=''),
        ),
    ]
