# Generated by Django 3.1.4 on 2020-12-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201212_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='account',
        ),
    ]
