# Generated by Django 3.1.4 on 2020-12-12 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rating_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ratings',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
