# Generated by Django 3.1.4 on 2020-12-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201212_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='averageRating',
        ),
    ]
