# Generated by Django 3.1.4 on 2020-12-13 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_restaurant_averagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='averageRating',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
