# Generated by Django 3.1.4 on 2020-12-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_restaurant_averagerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='averageRating',
        ),
    ]
