# Generated by Django 3.1.4 on 2020-12-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_restaurant_averagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='biography',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
