# Generated by Django 3.1.3 on 2020-12-15 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201215_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(related_name='friend_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
