# Generated by Django 3.1.3 on 2020-12-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201215_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
