# Generated by Django 3.1.4 on 2021-01-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210104_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='likes',
        ),
    ]
