# Generated by Django 3.1.4 on 2021-01-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210103_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='rd_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd_opened', models.IntegerField(default=0)),
            ],
        ),
    ]
