# Generated by Django 3.1.4 on 2021-01-05 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210105_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='fri',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='affordability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
