# Generated by Django 3.1.4 on 2021-01-04 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_restaurant_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(related_name='liked_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
