# Generated by Django 3.1.4 on 2021-01-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_restaurant_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rd_update',
        ),
    ]
