# Generated by Django 3.1.4 on 2021-01-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_restaurant_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(max_length=50, null=True)),
                ('tue', models.CharField(max_length=50, null=True)),
                ('wed', models.CharField(max_length=50, null=True)),
                ('thu', models.CharField(max_length=50, null=True)),
                ('fri', models.CharField(max_length=50, null=True)),
                ('sat', models.CharField(max_length=50, null=True)),
                ('sun', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='openingHours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hours'),
        ),
    ]
