# Generated by Django 3.1.4 on 2021-01-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210105_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
