# Generated by Django 3.1.4 on 2021-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210105_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='openingHours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fri',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
    ]
