# Generated by Django 3.1.4 on 2021-01-05 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210105_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='affordability',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
