# Generated by Django 3.1.4 on 2021-01-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_subcoment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcoment',
            new_name='Subcomment',
        ),
    ]
