# Generated by Django 3.1.4 on 2021-01-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rd_update'),
        ('accounts', '0027_auto_20210105_1206'),
        ('accounts', '0023_rd_update'),
    ]

    operations = [
    ]
