# Generated by Django 3.1.4 on 2021-01-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210108_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomment', to='accounts.comment'),
        ),
        migrations.DeleteModel(
            name='Subcomment',
        ),
    ]
