# Generated by Django 3.1.4 on 2021-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20210112_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='toGo',
            field=models.BooleanField(default=False),
        ),
    ]
