# Generated by Django 3.1.4 on 2021-01-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_food_togo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='toGo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
