# Generated by Django 3.1.4 on 2021-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_remove_food_togo'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='toGo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
