# Generated by Django 3.1.4 on 2021-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_food_togo'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='toGoPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coworker',
            name='bio',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='food',
            name='toGo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
