# Generated by Django 3.1.4 on 2021-01-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_food_togo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworker',
            name='bio',
            field=models.CharField(max_length=35),
        ),
    ]
