# Generated by Django 3.1.4 on 2021-01-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210123_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='toGoPrice',
        ),
        migrations.AddField(
            model_name='food',
            name='toGoAv',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='toGo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
