# Generated by Django 3.1.4 on 2021-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_remove_food_togoav'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='toGoAv',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
