# Generated by Django 3.1.4 on 2021-01-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_food_togoav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='toGoAv',
            new_name='delivery',
        ),
    ]
