# Generated by Django 3.1.4 on 2021-01-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210123_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='toGo',
            new_name='toGoPrice',
        ),
    ]
