# Generated by Django 3.1.4 on 2021-01-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20210123_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='toGoPrice',
        ),
    ]
