# Generated by Django 3.1.4 on 2021-01-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_food_togoprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='toGo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
