# Generated by Django 3.1.4 on 2021-01-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_food_togo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='delivery',
        ),
    ]
