# Generated by Django 3.1.4 on 2021-01-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_remove_food_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='delivery',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
