# Generated by Django 3.1.4 on 2021-01-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_food_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='delivery',
        ),
    ]
