# Generated by Django 3.1.4 on 2021-01-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210123_1811'),
        ('accounts', '0055_food_delivery'),
    ]

    operations = [
    ]
