# Generated by Django 3.1.4 on 2021-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_merge_20210123_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
