# Generated by Django 3.1.4 on 2021-01-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_restaurant_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='delivery',
        ),
    ]
