# Generated by Django 3.1.5 on 2021-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_remove_food_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
