# Generated by Django 3.1.5 on 2021-02-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_account_reset_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='toGo',
            new_name='toGoPrice',
        ),
    ]
