# Generated by Django 3.1.5 on 2021-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20210201_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientvalue',
            name='otherValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientvalue',
            name='otherValueName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
